---
# https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions
name: Release
"on":
  workflow_run:
    workflows: Test
    types: completed
    branches: release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#pushing-package.json-changes-to-a-master-branch
          # 当リポジトリのリリースブランチ（例：main）に対するブランチ保護が有効
          # な場合、次の行をアンコメントしてください。
          # persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: .settings/package-lock.json
      - name: "Install dependencies"
        run: npm i -D semantic-release
      - name: Release
        env:
          # https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#pushing-package.json-changes-to-a-master-branch
          # 当リポジトリのリリースブランチ（例：main）に対するブランチ保護が有効
          # な場合、`GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` を削除
          # またはコメントアウトし、その下の行をアンコメントしてください。
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        run: npx semantic-release
